# Generated by Django 4.2.5 on 2023-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
        ),
    ]
